BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '0'
            font_size: 48
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.increase_input(input_number.text)
            Button:
                text: 'Down'
                on_press: app.decrease_input(input_number.text)
    BoxLayout:
        orientation: 'vertical'
        Button:
            id: message_label
            text: 'Convert miles to km'
            on_press: app.handle_calculate(input_number.text)
        Label:
            id: output_label
            font_size: 48
            color: (1, 1, 0, 1)