BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '7'
            font_size: 48
        Button:
            text: 'Square'
            # the following line specifies the function in the app class to call when the button is pressed
            on_press: app.handle_calculate(input_number.text)
        Label:
            id: output_label
            font_size: 48
            color: (40, 245, 145, 0.8)
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: message_label
            text: 'Enter a number and press "Square"'
